name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: |
        swift build
        swift test
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
