name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: |
        xcodebuild -scheme RealityToolkit -destination "generic/platform=iOS Simulator"
        # Test isn't working with GH Actions, locally is fine.
        # xcodebuild test -scheme RealityToolkit -destination 'platform=macOS'
        swiftlint --strict